language: cpp

jobs:
  include:

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-9.2
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty']
env:
  - HOGE=fugafuga
  - PIYO="piyopiyo"
  global:
    - FOO=bar
    - VERSION=5.6

services:
  - docker

install:
  - env
  - sudo apt-get update -y 
  - sudo apt install -y --no-install-recommends libeigen3-dev cmake g++ clang-format clang-tidy
  - sudo apt-get clean
  - wget https://github.com/omnetpp/omnetpp/releases/download/omnetpp-$VERSION/omnetpp-$VERSION-src-linux.tgz --referer=https://omnetpp.org/ -O omnetpp-src-linux.tgz --progress=dot:giga && tar xf omnetpp-src-linux.tgz && rm omnetpp-src-linux.tgz
  - ls -la
  - pwd
  - cd omnetpp-src-linux && ./configure WITH_TKENV=no WITH_QTENV=no WITH_OSG=no WITH_OSGEARTH=no &&  make -j $(nproc)


script:
  - cd test && sudo python -m unittest discover && sudo rm testresults.txt && echo "test done"
branches:
  only:
    - master
    - Unittest
    - make-build-faster-2
