language: cpp

jobs:
  include:

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-9.2
      - VERSION=5.6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty']

install:
  - sudo apt-get update -y 
  - sudo apt install -y -q --no-install-recommends libeigen3-dev cmake g++ clang-format clang-tidy
  - sudo apt-get clean
  - cd ..
  - wget https://github.com/omnetpp/omnetpp/releases/download/omnetpp-$VERSION/omnetpp-$VERSION-src-linux.tgz --referer=https://omnetpp.org/ -O omnetpp-src-linux.tgz --progress=dot:giga && tar xf omnetpp-src-linux.tgz && rm omnetpp-src-linux.tgz
  - ls -la
  - pwd
  - cd omnetpp-$VERSION && export PATH=`pwd`/bin:$PATH && ./configure WITH_TKENV=no WITH_QTENV=no WITH_OSG=no WITH_OSGEARTH=no &&  make -j $(nproc)
  - cd ../quisp


script:
  - cd test && sudo python -m unittest discover && sudo rm testresults.txt && echo "test done"
branches:
  only:
    - master
    - Unittest
    - make-build-faster-2
