language: cpp

jobs:
  include:

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-9.2
      - VERSION=5.6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']

services:
  - docker

install:
  - docker build -f ./Dockerfile.travis --build-arg GTEST_VERSION=1.10.0 -t quisp .

script:
  - bash docker_run_lint.sh
  - docker run --rm -i -v "$TRAVIS_BUILD_DIR:/root/quisp" quisp /bin/sh -c "cd /root/quisp/test; /bin/bash test.sh"
  - cd test && sudo python -m unittest discover && sudo rm testresults.txt && echo "test done"
branches:
  only:
    - master
    - Unittest
    - make-build-faster-2
