language: cpp

jobs:
  include:

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-9.2
      - VERSION=5.6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty']

services:
  - docker

install:
  - sudo apt-get update -y 
  - sudo apt-get clean
  - docker build -f ./Dockerfile.travis --build-arg GTEST_VERSION=1.10.0 -t quisp .

script:
  - sh docker_run_lint.sh
  - sh docker_run_test.sh
  - cd test && sudo python -m unittest discover && sudo rm testresults.txt && echo "test done"
branches:
  only:
    - master
    - Unittest
    - make-build-faster-2
